# Generated by Django 5.1.1 on 2024-09-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='externalId',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='openId',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
