# Generated by Django 5.1.1 on 2024-09-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapi', '0003_alter_signer_externalid_alter_signer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signer',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
